# Generated by Django 5.0.2 on 2024-07-25 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcategory', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('child', 'child')], max_length=20, null=True)),
                ('pname', models.CharField(max_length=100)),
                ('pbrand', models.CharField(max_length=100)),
                ('pdesc', models.CharField(max_length=200)),
                ('pprice', models.PositiveIntegerField()),
                ('pimg', models.ImageField(default='', upload_to='addpicture/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(default='buyer', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=20)),
                ('profile', models.ImageField(default='', upload_to='picture/')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.addproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='addproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
