# Generated by Django 5.0.2 on 2024-07-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart_payment_status_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='product',
        ),
    ]
