# Generated by Django 5.0.2 on 2024-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
