# Generated by Django 5.0.2 on 2024-08-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_cart_product_price_alter_cart_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='pcategory',
            field=models.CharField(choices=[('apple', 'apple'), ('banana', 'banana'), ('kiwi', 'kiwi'), ('cherry', 'cherry'), ('mango', 'mango'), ('grapes', 'grapes')], max_length=20, null=True),
        ),
    ]
